
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type AddHost struct {
	ModuleName string
	Options AddHostOptions
	Result AddHostResult
}

type AddHostOptions struct {
	
		// Groups 
		Groups []string `yaml:"groups,omitempty" json:"groups,omitempty"`
	
		// Name 
		Name string `yaml:"name,omitempty" json:"name,omitempty"`
	
}

type AddHostResult struct {
	Raw string 
	
}

func (m *AddHost) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewAddHost() *AddHost {
	return &AddHost {
		ModuleName: "add_host",
	}
}
	