// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type Assert struct {
	ModuleName string
	Options    AssertOptions
	Result     AssertResult
}

type AssertOptions struct {

	// FailMsg
	FailMsg string `yaml:"fail_msg,omitempty" json:"fail_msg,omitempty"`

	// Quiet
	Quiet bool `yaml:"quiet,omitempty" json:"quiet,omitempty"`

	// SuccessMsg
	SuccessMsg string `yaml:"success_msg,omitempty" json:"success_msg,omitempty"`

	// That
	That []string `yaml:"that,omitempty" json:"that,omitempty"`
}

type AssertResult struct {
	Raw string
}

func (m *Assert) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewAssert() *Assert {
	return &Assert{
		ModuleName: "assert",
	}
}
