package module

// Autogenerated file

import (
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("async_status", func() Module {
		return NewAsyncStatus()
	})
}

//
// AsyncStatus (async_status) - Obtain status of asynchronous task
//
func NewAsyncStatus() *AsyncStatus {
	return &AsyncStatus{}
}

// AsyncStatus (async_status) - Obtain status of asynchronous task
//
// This module gets the status of an asynchronous task.
// This module is also supported for Windows targets.
//
// Source: https://github.com/ansible/ansible/blob/v2.13.1/lib/ansible/modules/async_status.py
type AsyncStatus struct {
	Params AsyncStatusParams
	Result AsyncStatusResult
}

type AsyncStatusParams struct {

	// Jid
	// Job or task identifier
	//
	// Default: <no value>
	// Required: true
	Jid string `yaml:"jid,omitempty" json:"jid,omitempty"`

	// Mode
	// If C(status), obtain the status.
	// If C(cleanup), clean up the async job cache (by default in C(~/.ansible_async/)) for the specified job I(jid).
	//
	// Default: status
	// Required: false
	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`
}

type AsyncStatusResult struct {
	types.CommonReturn
	Raw string

	// AnsibleJobId
	// The asynchronous job id
	AnsibleJobId string `yaml:"ansible_job_id,omitempty" json:"ansible_job_id,omitempty"`

	// Erased
	// Path to erased job file
	Erased string `yaml:"erased,omitempty" json:"erased,omitempty"`

	// Finished
	// Whether the asynchronous job has finished (C(1)) or not (C(0))
	Finished int `yaml:"finished,omitempty" json:"finished,omitempty"`

	// Started
	// Whether the asynchronous job has started (C(1)) or not (C(0))
	Started int `yaml:"started,omitempty" json:"started,omitempty"`

	// Stderr
	// Any errors returned by async_wrapper
	Stderr string `yaml:"stderr,omitempty" json:"stderr,omitempty"`

	// Stdout
	// Any output returned by async_wrapper
	Stdout string `yaml:"stdout,omitempty" json:"stdout,omitempty"`
}

func (m *AsyncStatus) GetResult() interface{} {
	return &m.Result
}

func (m *AsyncStatus) GetResultRaw() string {
	return m.Result.Raw
}

func (m *AsyncStatus) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *AsyncStatus) GetParams() interface{} {
	return &m.Params
}

func (m *AsyncStatus) GetType() string {
	return "async_status"
}
