// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

func init() {
	addModuleFactory("copy", func() Module {
		return NewCopy()
	})
}

type Copy struct {
	ModuleName string
	Params     CopyParams
	Result     CopyResult
}

type CopyParams struct {

	// Backup
	Backup bool `yaml:"backup,omitempty" json:"backup,omitempty"`

	// Checksum
	Checksum string `yaml:"checksum,omitempty" json:"checksum,omitempty"`

	// Content
	Content string `yaml:"content,omitempty" json:"content,omitempty"`

	// Dest
	Dest string `yaml:"dest,omitempty" json:"dest,omitempty"`

	// DirectoryMode
	DirectoryMode string `yaml:"directory_mode,omitempty" json:"directory_mode,omitempty"`

	// Follow
	Follow bool `yaml:"follow,omitempty" json:"follow,omitempty"`

	// Force
	Force bool `yaml:"force,omitempty" json:"force,omitempty"`

	// LocalFollow
	LocalFollow bool `yaml:"local_follow,omitempty" json:"local_follow,omitempty"`

	// Mode
	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`

	// RemoteSrc
	RemoteSrc bool `yaml:"remote_src,omitempty" json:"remote_src,omitempty"`

	// Src
	Src string `yaml:"src,omitempty" json:"src,omitempty"`
}

type CopyResult struct {
	Raw string

	// BackupFile
	BackupFile string `yaml:"backup_file,omitempty" json:"backup_file,omitempty"`

	// Checksum
	Checksum string `yaml:"checksum,omitempty" json:"checksum,omitempty"`

	// Dest
	Dest string `yaml:"dest,omitempty" json:"dest,omitempty"`

	// Gid
	Gid int `yaml:"gid,omitempty" json:"gid,omitempty"`

	// Group
	Group string `yaml:"group,omitempty" json:"group,omitempty"`

	// Md5sum
	Md5sum string `yaml:"md5sum,omitempty" json:"md5sum,omitempty"`

	// Mode
	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`

	// Owner
	Owner string `yaml:"owner,omitempty" json:"owner,omitempty"`

	// Size
	Size int `yaml:"size,omitempty" json:"size,omitempty"`

	// Src
	Src string `yaml:"src,omitempty" json:"src,omitempty"`

	// State
	State string `yaml:"state,omitempty" json:"state,omitempty"`

	// Uid
	Uid int `yaml:"uid,omitempty" json:"uid,omitempty"`
}

func (m *Copy) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func (m *Copy) GetResult() interface{} {
	return &m.Result
}

func (m *Copy) GetResultRaw() string {
	return m.Result.Raw
}

func (m *Copy) GetParams() interface{} {
	return &m.Params
}

func (m *Copy) GetType() string {
	return m.ModuleName
}

func NewCopy() *Copy {
	return &Copy{
		ModuleName: "copy",
	}
}
