package module

// Autogenerated file

import (
	"fmt"
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("debconf", func() types.Module {
		return NewDebconf()
	})
}

//
// Debconf (debconf) - Configure a .deb package
//
func NewDebconf() *Debconf {
	module := Debconf{}
	// Create dynamic param values
	paramValues := map[string]types.Value{}
	paramValues["name"] = types.NewStringValue(&module.Params.Name)
	paramValues["question"] = types.NewStringValue(&module.Params.Question)
	paramValues["unseen"] = types.NewBoolValue(&module.Params.Unseen)
	paramValues["value"] = types.NewStringValue(&module.Params.Value)
	paramValues["vtype"] = types.NewStringValue(&module.Params.Vtype)
	module.Params.values = paramValues

	// Create dynamic result values
	resultValues := map[string]types.Value{}

	module.Result.values = resultValues

	return &module
}

// Debconf (debconf) - Configure a .deb package
//
// Configure a .deb package using debconf-set-selections.
//
// Or just query existing selections.
//
//
// Source: https://github.com/ansible/ansible/blob/v2.13.1/lib/ansible/modules/debconf.py
type Debconf struct {
	Params DebconfParams
	Result DebconfResult
}

type DebconfParams struct {

	// Name
	// Name of package to configure.
	//
	// Default: <no value>
	// Required: true
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	// Question
	// A debconf configuration setting.
	//
	// Default: <no value>
	// Required: false
	Question string `yaml:"question,omitempty" json:"question,omitempty"`

	// Unseen
	// Do not set 'seen' flag when pre-seeding.
	//
	// Default: false
	// Required: false
	Unseen bool `yaml:"unseen,omitempty" json:"unseen,omitempty"`

	// Value
	// Value to set the configuration to.
	//
	// Default: <no value>
	// Required: false
	Value string `yaml:"value,omitempty" json:"value,omitempty"`

	// Vtype
	// The type of the value supplied.
	// It is highly recommended to add I(no_log=True) to task while specifying I(vtype=password).
	// C(seen) was added in Ansible 2.2.
	//
	// Default: <no value>
	// Required: false
	Vtype string `yaml:"vtype,omitempty" json:"vtype,omitempty"`

	values map[string]types.Value
}

func (p *DebconfParams) Names() []string {
	names := []string{}
	for name := range p.values {
		names = append(names, name)
	}
	return []string{}
}

func (p *DebconfParams) Set(name string, value interface{}) error {
	v, ok := p.values[name]
	if !ok {
		return fmt.Errorf("no param with name %q", name)
	}
	return v.Set(value)
}

func (p *DebconfParams) Get(name string) (interface{}, error) {
	v, ok := p.values[name]
	if !ok {
		return nil, fmt.Errorf("no param with name %q", name)
	}
	return v.Get(), nil
}

type DebconfResult struct {
	types.CommonReturn
	Raw string

	values map[string]types.Value
}

func (r *DebconfResult) Names() []string {
	names := []string{}
	for name := range r.values {
		names = append(names, name)
	}
	return []string{}
}

func (r *DebconfResult) Set(name string, value interface{}) error {
	v, ok := r.values[name]
	if !ok {
		return fmt.Errorf("no param with name %q", name)
	}
	return v.Set(value)
}

func (r *DebconfResult) Get(name string) (interface{}, error) {
	v, ok := r.values[name]
	if !ok {
		return nil, fmt.Errorf("no param with name %q", name)
	}
	return v.Get(), nil
}

func (m *Debconf) GetResult() types.Result {
	return &m.Result
}

func (m *Debconf) GetResultRaw() string {
	return m.Result.Raw
}

func (m *Debconf) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *Debconf) GetParams() types.Params {
	return &m.Params
}

func (m *Debconf) GetType() string {
	return "debconf"
}
