// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

func init() {
	addModuleFactory("dpkg_selections", func() Module {
		return NewDpkgSelections()
	})
}

type DpkgSelections struct {
	ModuleName string
	Params     DpkgSelectionsParams
	Result     DpkgSelectionsResult
}

type DpkgSelectionsParams struct {

	// Name
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	// Selection
	Selection string `yaml:"selection,omitempty" json:"selection,omitempty"`
}

type DpkgSelectionsResult struct {
	Raw string
}

func (m *DpkgSelections) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func (m *DpkgSelections) GetResult() interface{} {
	return &m.Result
}

func (m *DpkgSelections) GetResultRaw() string {
	return m.Result.Raw
}

func (m *DpkgSelections) GetParams() interface{} {
	return &m.Params
}

func (m *DpkgSelections) GetType() string {
	return m.ModuleName
}

func NewDpkgSelections() *DpkgSelections {
	return &DpkgSelections{
		ModuleName: "dpkg_selections",
	}
}
