// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type Fail struct {
	ModuleName string
	Options    FailOptions
	Result     FailResult
}

type FailOptions struct {

	// Msg
	Msg string `yaml:"msg,omitempty" json:"msg,omitempty"`
}

type FailResult struct {
	Raw string
}

func (m *Fail) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewFail() *Fail {
	return &Fail{
		ModuleName: "fail",
	}
}
