// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type Fetch struct {
	ModuleName string
	Options    FetchOptions
	Result     FetchResult
}

type FetchOptions struct {

	// Dest
	Dest string `yaml:"dest,omitempty" json:"dest,omitempty"`

	// FailOnMissing
	FailOnMissing bool `yaml:"fail_on_missing,omitempty" json:"fail_on_missing,omitempty"`

	// Flat
	Flat bool `yaml:"flat,omitempty" json:"flat,omitempty"`

	// Src
	Src string `yaml:"src,omitempty" json:"src,omitempty"`

	// ValidateChecksum
	ValidateChecksum bool `yaml:"validate_checksum,omitempty" json:"validate_checksum,omitempty"`
}

type FetchResult struct {
	Raw string
}

func (m *Fetch) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewFetch() *Fetch {
	return &Fetch{
		ModuleName: "fetch",
	}
}
