// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type File struct {
	ModuleName string
	Options    FileOptions
	Result     FileResult
}

type FileOptions struct {

	// AccessTime
	AccessTime string `yaml:"access_time,omitempty" json:"access_time,omitempty"`

	// AccessTimeFormat
	AccessTimeFormat string `yaml:"access_time_format,omitempty" json:"access_time_format,omitempty"`

	// Follow
	Follow bool `yaml:"follow,omitempty" json:"follow,omitempty"`

	// Force
	Force bool `yaml:"force,omitempty" json:"force,omitempty"`

	// ModificationTime
	ModificationTime string `yaml:"modification_time,omitempty" json:"modification_time,omitempty"`

	// ModificationTimeFormat
	ModificationTimeFormat string `yaml:"modification_time_format,omitempty" json:"modification_time_format,omitempty"`

	// Path
	Path string `yaml:"path,omitempty" json:"path,omitempty"`

	// Recurse
	Recurse bool `yaml:"recurse,omitempty" json:"recurse,omitempty"`

	// Src
	Src string `yaml:"src,omitempty" json:"src,omitempty"`

	// State
	State string `yaml:"state,omitempty" json:"state,omitempty"`
}

type FileResult struct {
	Raw string

	// Dest
	Dest string `yaml:"dest,omitempty" json:"dest,omitempty"`

	// Path
	Path string `yaml:"path,omitempty" json:"path,omitempty"`
}

func (m *File) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewFile() *File {
	return &File{
		ModuleName: "file",
	}
}
