// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type GatherFacts struct {
	ModuleName string
	Options    GatherFactsOptions
	Result     GatherFactsResult
}

type GatherFactsOptions struct {

	// Parallel
	Parallel bool `yaml:"parallel,omitempty" json:"parallel,omitempty"`
}

type GatherFactsResult struct {
	Raw string
}

func (m *GatherFacts) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewGatherFacts() *GatherFacts {
	return &GatherFacts{
		ModuleName: "gather_facts",
	}
}
