// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

type Getent struct {
	ModuleName string
	Params     GetentParams
	Result     GetentResult
}

type GetentParams struct {

	// Database
	Database string `yaml:"database,omitempty" json:"database,omitempty"`

	// FailKey
	FailKey bool `yaml:"fail_key,omitempty" json:"fail_key,omitempty"`

	// Key
	Key string `yaml:"key,omitempty" json:"key,omitempty"`

	// Service
	Service string `yaml:"service,omitempty" json:"service,omitempty"`

	// Split
	Split string `yaml:"split,omitempty" json:"split,omitempty"`
}

type GetentResult struct {
	Raw string

	// AnsibleFacts
	AnsibleFacts map[string]interface{} `yaml:"ansible_facts,omitempty" json:"ansible_facts,omitempty"`
}

func (m *Getent) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewGetent() *Getent {
	return &Getent{
		ModuleName: "getent",
	}
}
