
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type GroupBy struct {
	ModuleName string
	Options GroupByOptions
	Result GroupByResult
}

type GroupByOptions struct {
	
		// Key 
		Key string `yaml:"key,omitempty" json:"key,omitempty"`
	
		// Parents 
		Parents []string `yaml:"parents,omitempty" json:"parents,omitempty"`
	
}

type GroupByResult struct {
	Raw string 
	
}

func (m *GroupBy) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewGroupBy() *GroupBy {
	return &GroupBy {
		ModuleName: "group_by",
	}
}
	