
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type Hostname struct {
	ModuleName string
	Options HostnameOptions
	Result HostnameResult
}

type HostnameOptions struct {
	
		// Name 
		Name string `yaml:"name,omitempty" json:"name,omitempty"`
	
		// Use 
		Use string `yaml:"use,omitempty" json:"use,omitempty"`
	
}

type HostnameResult struct {
	Raw string 
	
}

func (m *Hostname) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewHostname() *Hostname {
	return &Hostname {
		ModuleName: "hostname",
	}
}
	