// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type ImportTasks struct {
	ModuleName string
	Options    ImportTasksOptions
	Result     ImportTasksResult
}

type ImportTasksOptions struct {

	// FreeForm
	FreeForm string `yaml:"free-form,omitempty" json:"free-form,omitempty"`
}

type ImportTasksResult struct {
	Raw string
}

func (m *ImportTasks) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewImportTasks() *ImportTasks {
	return &ImportTasks{
		ModuleName: "import_tasks",
	}
}
