
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type ImportRole struct {
	ModuleName string
	Options ImportRoleOptions
	Result ImportRoleResult
}

type ImportRoleOptions struct {
	
		// AllowDuplicates 
		AllowDuplicates bool `yaml:"allow_duplicates,omitempty" json:"allow_duplicates,omitempty"`
	
		// DefaultsFrom 
		DefaultsFrom string `yaml:"defaults_from,omitempty" json:"defaults_from,omitempty"`
	
		// HandlersFrom 
		HandlersFrom string `yaml:"handlers_from,omitempty" json:"handlers_from,omitempty"`
	
		// Name 
		Name string `yaml:"name,omitempty" json:"name,omitempty"`
	
		// RolespecValidate 
		RolespecValidate bool `yaml:"rolespec_validate,omitempty" json:"rolespec_validate,omitempty"`
	
		// TasksFrom 
		TasksFrom string `yaml:"tasks_from,omitempty" json:"tasks_from,omitempty"`
	
		// VarsFrom 
		VarsFrom string `yaml:"vars_from,omitempty" json:"vars_from,omitempty"`
	
}

type ImportRoleResult struct {
	Raw string 
	
}

func (m *ImportRole) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewImportRole() *ImportRole {
	return &ImportRole {
		ModuleName: "import_role",
	}
}
	