
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type IncludeRole struct {
	ModuleName string
	Options IncludeRoleOptions
	Result IncludeRoleResult
}

type IncludeRoleOptions struct {
	
		// AllowDuplicates 
		AllowDuplicates bool `yaml:"allow_duplicates,omitempty" json:"allow_duplicates,omitempty"`
	
		// Apply 
		Apply string `yaml:"apply,omitempty" json:"apply,omitempty"`
	
		// DefaultsFrom 
		DefaultsFrom string `yaml:"defaults_from,omitempty" json:"defaults_from,omitempty"`
	
		// HandlersFrom 
		HandlersFrom string `yaml:"handlers_from,omitempty" json:"handlers_from,omitempty"`
	
		// Name 
		Name string `yaml:"name,omitempty" json:"name,omitempty"`
	
		// Public 
		Public bool `yaml:"public,omitempty" json:"public,omitempty"`
	
		// RolespecValidate 
		RolespecValidate bool `yaml:"rolespec_validate,omitempty" json:"rolespec_validate,omitempty"`
	
		// TasksFrom 
		TasksFrom string `yaml:"tasks_from,omitempty" json:"tasks_from,omitempty"`
	
		// VarsFrom 
		VarsFrom string `yaml:"vars_from,omitempty" json:"vars_from,omitempty"`
	
}

type IncludeRoleResult struct {
	Raw string 
	
}

func (m *IncludeRole) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewIncludeRole() *IncludeRole {
	return &IncludeRole {
		ModuleName: "include_role",
	}
}
	