
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type IncludeTasks struct {
	ModuleName string
	Options IncludeTasksOptions
	Result IncludeTasksResult
}

type IncludeTasksOptions struct {
	
		// Apply 
		Apply string `yaml:"apply,omitempty" json:"apply,omitempty"`
	
		// File 
		File string `yaml:"file,omitempty" json:"file,omitempty"`
	
		// FreeForm 
		FreeForm string `yaml:"free-form,omitempty" json:"free-form,omitempty"`
	
}

type IncludeTasksResult struct {
	Raw string 
	
}

func (m *IncludeTasks) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewIncludeTasks() *IncludeTasks {
	return &IncludeTasks {
		ModuleName: "include_tasks",
	}
}
	