// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("known_hosts", func() Module {
		return NewKnownHosts()
	})
}

type KnownHosts struct {
	ModuleName string
	Params     KnownHostsParams
	Result     KnownHostsResult
}

type KnownHostsParams struct {

	// HashHost
	HashHost bool `yaml:"hash_host,omitempty" json:"hash_host,omitempty"`

	// Key
	Key string `yaml:"key,omitempty" json:"key,omitempty"`

	// Name
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	// Path
	Path string `yaml:"path,omitempty" json:"path,omitempty"`

	// State
	State string `yaml:"state,omitempty" json:"state,omitempty"`
}

type KnownHostsResult struct {
	types.CommonReturn
	Raw string
}

func (m *KnownHosts) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func (m *KnownHosts) GetResult() interface{} {
	return &m.Result
}

func (m *KnownHosts) GetResultRaw() string {
	return m.Result.Raw
}

func (m *KnownHosts) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *KnownHosts) GetParams() interface{} {
	return &m.Params
}

func (m *KnownHosts) GetType() string {
	return m.ModuleName
}

func NewKnownHosts() *KnownHosts {
	return &KnownHosts{
		ModuleName: "known_hosts",
	}
}
