
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type Meta struct {
	ModuleName string
	Options MetaOptions
	Result MetaResult
}

type MetaOptions struct {
	
		// FreeForm 
		FreeForm string `yaml:"free_form,omitempty" json:"free_form,omitempty"`
	
}

type MetaResult struct {
	Raw string 
	
}

func (m *Meta) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewMeta() *Meta {
	return &Meta {
		ModuleName: "meta",
	}
}
	