// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

func init() {
	addModuleFactory("meta", func() Module {
		return NewMeta()
	})
}

type Meta struct {
	ModuleName string
	Params     MetaParams
	Result     MetaResult
}

type MetaParams struct {

	// FreeForm
	FreeForm string `yaml:"free_form,omitempty" json:"free_form,omitempty"`
}

type MetaResult struct {
	Raw string
}

func (m *Meta) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func (m *Meta) GetResult() interface{} {
	return &m.Result
}

func (m *Meta) GetResultRaw() string {
	return m.Result.Raw
}

func (m *Meta) GetParams() interface{} {
	return &m.Params
}

func (m *Meta) GetType() string {
	return m.ModuleName
}

func NewMeta() *Meta {
	return &Meta{
		ModuleName: "meta",
	}
}
