package module

// Autogenerated file

import (
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("package_facts", func() Module {
		return NewPackageFacts()
	})
}

//
// PackageFacts (package_facts) - Package information as facts
//
func NewPackageFacts() *PackageFacts {
	return &PackageFacts{}
}

// PackageFacts (package_facts) - Package information as facts
//
// Return information about installed packages as facts.
type PackageFacts struct {
	Params PackageFactsParams
	Result PackageFactsResult
}

type PackageFactsParams struct {

	// Manager
	// The package manager used by the system so we can query the package information.
	// Since 2.8 this is a list and can support multiple package managers per system.
	// The 'portage' and 'pkg' options were added in version 2.8.
	// The 'apk' option was added in version 2.11.
	// The 'pkg_info' option was added in version 2.13.
	//
	// Default: [auto]
	// Required: false
	Manager []string `yaml:"manager,omitempty" json:"manager,omitempty"`

	// Strategy
	// This option controls how the module queries the package managers on the system. C(first) means it will return only information for the first supported package manager available. C(all) will return information for all supported and available package managers on the system.
	//
	// Default: first
	// Required: false
	Strategy string `yaml:"strategy,omitempty" json:"strategy,omitempty"`
}

type PackageFactsResult struct {
	types.CommonReturn
	Raw string

	// AnsibleFacts
	// Facts to add to ansible_facts.
	AnsibleFacts interface{} `yaml:"ansible_facts,omitempty" json:"ansible_facts,omitempty"`
}

func (m *PackageFacts) GetResult() interface{} {
	return &m.Result
}

func (m *PackageFacts) GetResultRaw() string {
	return m.Result.Raw
}

func (m *PackageFacts) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *PackageFacts) GetParams() interface{} {
	return &m.Params
}

func (m *PackageFacts) GetType() string {
	return "package_facts"
}
