// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type PackageFacts struct {
	ModuleName string
	Options    PackageFactsOptions
	Result     PackageFactsResult
}

type PackageFactsOptions struct {

	// Manager
	Manager []string `yaml:"manager,omitempty" json:"manager,omitempty"`

	// Strategy
	Strategy string `yaml:"strategy,omitempty" json:"strategy,omitempty"`
}

type PackageFactsResult struct {
	Raw string

	// AnsibleFacts
	AnsibleFacts interface{} `yaml:"ansible_facts,omitempty" json:"ansible_facts,omitempty"`
}

func (m *PackageFacts) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewPackageFacts() *PackageFacts {
	return &PackageFacts{
		ModuleName: "package_facts",
	}
}
