// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

func init() {
	addModuleFactory("package_facts", func() Module {
		return NewPackageFacts()
	})
}

type PackageFacts struct {
	ModuleName string
	Params     PackageFactsParams
	Result     PackageFactsResult
}

type PackageFactsParams struct {

	// Manager
	Manager []string `yaml:"manager,omitempty" json:"manager,omitempty"`

	// Strategy
	Strategy string `yaml:"strategy,omitempty" json:"strategy,omitempty"`
}

type PackageFactsResult struct {
	Raw string

	// AnsibleFacts
	AnsibleFacts interface{} `yaml:"ansible_facts,omitempty" json:"ansible_facts,omitempty"`
}

func (m *PackageFacts) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func (m *PackageFacts) GetResult() interface{} {
	return &m.Result
}

func (m *PackageFacts) GetResultRaw() string {
	return m.Result.Raw
}

func (m *PackageFacts) GetParams() interface{} {
	return &m.Params
}

func (m *PackageFacts) GetType() string {
	return m.ModuleName
}

func NewPackageFacts() *PackageFacts {
	return &PackageFacts{
		ModuleName: "package_facts",
	}
}
