// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type Ping struct {
	ModuleName string
	Params     PingParams
	Result     PingResult
}

type PingParams struct {

	// Data
	Data string `yaml:"data,omitempty" json:"data,omitempty"`
}

type PingResult struct {
	Raw string

	// Ping
	Ping string `yaml:"ping,omitempty" json:"ping,omitempty"`
}

func (m *Ping) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewPing() *Ping {
	return &Ping{
		ModuleName: "ping",
	}
}
