package module

// Autogenerated file

import (
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("rpm_key", func() Module {
		return NewRpmKey()
	})
}

//
// RpmKey (rpm_key) - Adds or removes a gpg key from the rpm db
//
func NewRpmKey() *RpmKey {
	return &RpmKey{}
}

// RpmKey (rpm_key) - Adds or removes a gpg key from the rpm db
//
// Adds or removes (rpm --import) a gpg key to your rpm database.
//
// Source: https://github.com/ansible/ansible/blob/v2.13.1/lib/ansible/modules/rpm_key.py
type RpmKey struct {
	Params RpmKeyParams
	Result RpmKeyResult
}

type RpmKeyParams struct {

	// Fingerprint
	// The long-form fingerprint of the key being imported.
	// This will be used to verify the specified key.
	//
	// Default: <no value>
	// Required: false
	Fingerprint string `yaml:"fingerprint,omitempty" json:"fingerprint,omitempty"`

	// Key
	// Key that will be modified. Can be a url, a file on the managed node, or a keyid if the key already exists in the database.
	//
	// Default: <no value>
	// Required: true
	Key string `yaml:"key,omitempty" json:"key,omitempty"`

	// State
	// If the key will be imported or removed from the rpm db.
	//
	// Default: present
	// Required: false
	State string `yaml:"state,omitempty" json:"state,omitempty"`

	// ValidateCerts
	// If C(no) and the C(key) is a url starting with https, SSL certificates will not be validated.
	// This should only be used on personally controlled sites using self-signed certificates.
	//
	// Default: yes
	// Required: false
	ValidateCerts bool `yaml:"validate_certs,omitempty" json:"validate_certs,omitempty"`
}

type RpmKeyResult struct {
	types.CommonReturn
	Raw string
}

func (m *RpmKey) GetResult() interface{} {
	return &m.Result
}

func (m *RpmKey) GetResultRaw() string {
	return m.Result.Raw
}

func (m *RpmKey) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *RpmKey) GetParams() interface{} {
	return &m.Params
}

func (m *RpmKey) GetType() string {
	return "rpm_key"
}
