// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type Script struct {
	ModuleName string
	Params     ScriptParams
	Result     ScriptResult
}

type ScriptParams struct {

	// Chdir
	Chdir string `yaml:"chdir,omitempty" json:"chdir,omitempty"`

	// Cmd
	Cmd string `yaml:"cmd,omitempty" json:"cmd,omitempty"`

	// Creates
	Creates string `yaml:"creates,omitempty" json:"creates,omitempty"`

	// Executable
	Executable string `yaml:"executable,omitempty" json:"executable,omitempty"`

	// FreeForm
	FreeForm string `yaml:"free_form,omitempty" json:"free_form,omitempty"`

	// Removes
	Removes string `yaml:"removes,omitempty" json:"removes,omitempty"`
}

type ScriptResult struct {
	Raw string
}

func (m *Script) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewScript() *Script {
	return &Script{
		ModuleName: "script",
	}
}
