package module

// Autogenerated file

import (
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("service_facts", func() Module {
		return NewServiceFacts()
	})
}

//
// ServiceFacts (service_facts) - Return service state information as fact data
//
func NewServiceFacts() *ServiceFacts {
	return &ServiceFacts{}
}

// ServiceFacts (service_facts) - Return service state information as fact data
//
// Return service state information as fact data for various service management utilities.
type ServiceFacts struct {
	Params ServiceFactsParams
	Result ServiceFactsResult
}

type ServiceFactsParams struct {
}

type ServiceFactsResult struct {
	types.CommonReturn
	Raw string

	// AnsibleFacts
	// Facts to add to ansible_facts about the services on the system
	AnsibleFacts interface{} `yaml:"ansible_facts,omitempty" json:"ansible_facts,omitempty"`
}

func (m *ServiceFacts) GetResult() interface{} {
	return &m.Result
}

func (m *ServiceFacts) GetResultRaw() string {
	return m.Result.Raw
}

func (m *ServiceFacts) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *ServiceFacts) GetParams() interface{} {
	return &m.Params
}

func (m *ServiceFacts) GetType() string {
	return "service_facts"
}
