// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
	"github.com/weakpixel/aig/pkg/types"
)

func init() {
	addModuleFactory("service_facts", func() Module {
		return NewServiceFacts()
	})
}

type ServiceFacts struct {
	ModuleName string
	Params     ServiceFactsParams
	Result     ServiceFactsResult
}

type ServiceFactsParams struct {
}

type ServiceFactsResult struct {
	types.CommonReturn
	Raw string

	// AnsibleFacts
	AnsibleFacts interface{} `yaml:"ansible_facts,omitempty" json:"ansible_facts,omitempty"`
}

func (m *ServiceFacts) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func (m *ServiceFacts) GetResult() interface{} {
	return &m.Result
}

func (m *ServiceFacts) GetResultRaw() string {
	return m.Result.Raw
}

func (m *ServiceFacts) GetCommonResult() types.CommonReturn {
	return m.Result.CommonReturn
}

func (m *ServiceFacts) GetParams() interface{} {
	return &m.Params
}

func (m *ServiceFacts) GetType() string {
	return m.ModuleName
}

func NewServiceFacts() *ServiceFacts {
	return &ServiceFacts{
		ModuleName: "service_facts",
	}
}
