// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type SetStats struct {
	ModuleName string
	Params     SetStatsParams
	Result     SetStatsResult
}

type SetStatsParams struct {

	// Aggregate
	Aggregate bool `yaml:"aggregate,omitempty" json:"aggregate,omitempty"`

	// Data
	Data map[string]interface{} `yaml:"data,omitempty" json:"data,omitempty"`

	// PerHost
	PerHost bool `yaml:"per_host,omitempty" json:"per_host,omitempty"`
}

type SetStatsResult struct {
	Raw string
}

func (m *SetStats) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewSetStats() *SetStats {
	return &SetStats{
		ModuleName: "set_stats",
	}
}
