// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type SetFact struct {
	ModuleName string
	Options    SetFactOptions
	Result     SetFactResult
}

type SetFactOptions struct {

	// Cacheable
	Cacheable bool `yaml:"cacheable,omitempty" json:"cacheable,omitempty"`

	// KeyValue
	KeyValue string `yaml:"key_value,omitempty" json:"key_value,omitempty"`
}

type SetFactResult struct {
	Raw string
}

func (m *SetFact) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewSetFact() *SetFact {
	return &SetFact{
		ModuleName: "set_fact",
	}
}
