// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

type Setup struct {
	ModuleName string
	Params     SetupParams
	Result     SetupResult
}

type SetupParams struct {

	// FactPath
	FactPath string `yaml:"fact_path,omitempty" json:"fact_path,omitempty"`

	// Filter
	Filter []string `yaml:"filter,omitempty" json:"filter,omitempty"`

	// GatherSubset
	GatherSubset []string `yaml:"gather_subset,omitempty" json:"gather_subset,omitempty"`

	// GatherTimeout
	GatherTimeout int `yaml:"gather_timeout,omitempty" json:"gather_timeout,omitempty"`
}

type SetupResult struct {
	Raw string
}

func (m *Setup) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewSetup() *Setup {
	return &Setup{
		ModuleName: "setup",
	}
}
