
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type Stat struct {
	ModuleName string
	Options StatOptions
	Result StatResult
}

type StatOptions struct {
	
		// ChecksumAlgorithm 
		ChecksumAlgorithm string `yaml:"checksum_algorithm,omitempty" json:"checksum_algorithm,omitempty"`
	
		// Follow 
		Follow bool `yaml:"follow,omitempty" json:"follow,omitempty"`
	
		// GetAttributes 
		GetAttributes bool `yaml:"get_attributes,omitempty" json:"get_attributes,omitempty"`
	
		// GetChecksum 
		GetChecksum bool `yaml:"get_checksum,omitempty" json:"get_checksum,omitempty"`
	
		// GetMime 
		GetMime bool `yaml:"get_mime,omitempty" json:"get_mime,omitempty"`
	
		// Path 
		Path string `yaml:"path,omitempty" json:"path,omitempty"`
	
}

type StatResult struct {
	Raw string 
	
		// Stat 
		Stat interface{} `yaml:"stat,omitempty" json:"stat,omitempty"`
	
}

func (m *Stat) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewStat() *Stat {
	return &Stat {
		ModuleName: "stat",
	}
}
	