
// Autogenerated
package module

import (
	"aig/pkg/ansible"
	
)

type Template struct {
	ModuleName string
	Options TemplateOptions
	Result TemplateResult
}

type TemplateOptions struct {
	
		// Follow 
		Follow bool `yaml:"follow,omitempty" json:"follow,omitempty"`
	
}

type TemplateResult struct {
	Raw string 
	
}

func (m *Template) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Options, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewTemplate() *Template {
	return &Template {
		ModuleName: "template",
	}
}
	