// Autogenerated
package module

import (
	"aig/pkg/ansible"
)

type Uri struct {
	ModuleName string
	Params     UriParams
	Result     UriResult
}

type UriParams struct {

	// Body
	Body string `yaml:"body,omitempty" json:"body,omitempty"`

	// BodyFormat
	BodyFormat string `yaml:"body_format,omitempty" json:"body_format,omitempty"`

	// CaPath
	CaPath string `yaml:"ca_path,omitempty" json:"ca_path,omitempty"`

	// ClientCert
	ClientCert string `yaml:"client_cert,omitempty" json:"client_cert,omitempty"`

	// ClientKey
	ClientKey string `yaml:"client_key,omitempty" json:"client_key,omitempty"`

	// Creates
	Creates string `yaml:"creates,omitempty" json:"creates,omitempty"`

	// Dest
	Dest string `yaml:"dest,omitempty" json:"dest,omitempty"`

	// FollowRedirects
	FollowRedirects string `yaml:"follow_redirects,omitempty" json:"follow_redirects,omitempty"`

	// Force
	Force bool `yaml:"force,omitempty" json:"force,omitempty"`

	// ForceBasicAuth
	ForceBasicAuth bool `yaml:"force_basic_auth,omitempty" json:"force_basic_auth,omitempty"`

	// Headers
	Headers map[string]interface{} `yaml:"headers,omitempty" json:"headers,omitempty"`

	// HttpAgent
	HttpAgent string `yaml:"http_agent,omitempty" json:"http_agent,omitempty"`

	// Method
	Method string `yaml:"method,omitempty" json:"method,omitempty"`

	// RemoteSrc
	RemoteSrc bool `yaml:"remote_src,omitempty" json:"remote_src,omitempty"`

	// Removes
	Removes string `yaml:"removes,omitempty" json:"removes,omitempty"`

	// ReturnContent
	ReturnContent bool `yaml:"return_content,omitempty" json:"return_content,omitempty"`

	// Src
	Src string `yaml:"src,omitempty" json:"src,omitempty"`

	// StatusCode
	StatusCode []int `yaml:"status_code,omitempty" json:"status_code,omitempty"`

	// Timeout
	Timeout int `yaml:"timeout,omitempty" json:"timeout,omitempty"`

	// UnixSocket
	UnixSocket string `yaml:"unix_socket,omitempty" json:"unix_socket,omitempty"`

	// UnredirectedHeaders
	UnredirectedHeaders []string `yaml:"unredirected_headers,omitempty" json:"unredirected_headers,omitempty"`

	// Url
	Url string `yaml:"url,omitempty" json:"url,omitempty"`

	// UrlPassword
	UrlPassword string `yaml:"url_password,omitempty" json:"url_password,omitempty"`

	// UrlUsername
	UrlUsername string `yaml:"url_username,omitempty" json:"url_username,omitempty"`

	// UseGssapi
	UseGssapi bool `yaml:"use_gssapi,omitempty" json:"use_gssapi,omitempty"`

	// UseProxy
	UseProxy bool `yaml:"use_proxy,omitempty" json:"use_proxy,omitempty"`

	// ValidateCerts
	ValidateCerts bool `yaml:"validate_certs,omitempty" json:"validate_certs,omitempty"`
}

type UriResult struct {
	Raw string

	// Content
	Content string `yaml:"content,omitempty" json:"content,omitempty"`

	// Cookies
	Cookies map[string]interface{} `yaml:"cookies,omitempty" json:"cookies,omitempty"`

	// CookiesString
	CookiesString string `yaml:"cookies_string,omitempty" json:"cookies_string,omitempty"`

	// Elapsed
	Elapsed int `yaml:"elapsed,omitempty" json:"elapsed,omitempty"`

	// Msg
	Msg string `yaml:"msg,omitempty" json:"msg,omitempty"`

	// Path
	Path string `yaml:"path,omitempty" json:"path,omitempty"`

	// Redirected
	Redirected bool `yaml:"redirected,omitempty" json:"redirected,omitempty"`

	// Status
	Status int `yaml:"status,omitempty" json:"status,omitempty"`

	// Url
	Url string `yaml:"url,omitempty" json:"url,omitempty"`
}

func (m *Uri) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewUri() *Uri {
	return &Uri{
		ModuleName: "uri",
	}
}
