// Autogenerated
package module

import (
	"github.com/weakpixel/aig/pkg/ansible"
)

type User struct {
	ModuleName string
	Params     UserParams
	Result     UserResult
}

type UserParams struct {

	// Append
	Append bool `yaml:"append,omitempty" json:"append,omitempty"`

	// Authorization
	Authorization string `yaml:"authorization,omitempty" json:"authorization,omitempty"`

	// Comment
	Comment string `yaml:"comment,omitempty" json:"comment,omitempty"`

	// CreateHome
	CreateHome bool `yaml:"create_home,omitempty" json:"create_home,omitempty"`

	// Expires
	Expires float64 `yaml:"expires,omitempty" json:"expires,omitempty"`

	// Force
	Force bool `yaml:"force,omitempty" json:"force,omitempty"`

	// GenerateSshKey
	GenerateSshKey bool `yaml:"generate_ssh_key,omitempty" json:"generate_ssh_key,omitempty"`

	// Group
	Group string `yaml:"group,omitempty" json:"group,omitempty"`

	// Groups
	Groups []string `yaml:"groups,omitempty" json:"groups,omitempty"`

	// Hidden
	Hidden bool `yaml:"hidden,omitempty" json:"hidden,omitempty"`

	// Home
	Home string `yaml:"home,omitempty" json:"home,omitempty"`

	// Local
	Local bool `yaml:"local,omitempty" json:"local,omitempty"`

	// LoginClass
	LoginClass string `yaml:"login_class,omitempty" json:"login_class,omitempty"`

	// MoveHome
	MoveHome bool `yaml:"move_home,omitempty" json:"move_home,omitempty"`

	// Name
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	// NonUnique
	NonUnique bool `yaml:"non_unique,omitempty" json:"non_unique,omitempty"`

	// Password
	Password string `yaml:"password,omitempty" json:"password,omitempty"`

	// PasswordExpireMax
	PasswordExpireMax int `yaml:"password_expire_max,omitempty" json:"password_expire_max,omitempty"`

	// PasswordExpireMin
	PasswordExpireMin int `yaml:"password_expire_min,omitempty" json:"password_expire_min,omitempty"`

	// PasswordLock
	PasswordLock bool `yaml:"password_lock,omitempty" json:"password_lock,omitempty"`

	// Profile
	Profile string `yaml:"profile,omitempty" json:"profile,omitempty"`

	// Remove
	Remove bool `yaml:"remove,omitempty" json:"remove,omitempty"`

	// Role
	Role string `yaml:"role,omitempty" json:"role,omitempty"`

	// Seuser
	Seuser string `yaml:"seuser,omitempty" json:"seuser,omitempty"`

	// Shell
	Shell string `yaml:"shell,omitempty" json:"shell,omitempty"`

	// Skeleton
	Skeleton string `yaml:"skeleton,omitempty" json:"skeleton,omitempty"`

	// SshKeyBits
	SshKeyBits int `yaml:"ssh_key_bits,omitempty" json:"ssh_key_bits,omitempty"`

	// SshKeyComment
	SshKeyComment string `yaml:"ssh_key_comment,omitempty" json:"ssh_key_comment,omitempty"`

	// SshKeyFile
	SshKeyFile string `yaml:"ssh_key_file,omitempty" json:"ssh_key_file,omitempty"`

	// SshKeyPassphrase
	SshKeyPassphrase string `yaml:"ssh_key_passphrase,omitempty" json:"ssh_key_passphrase,omitempty"`

	// SshKeyType
	SshKeyType string `yaml:"ssh_key_type,omitempty" json:"ssh_key_type,omitempty"`

	// State
	State string `yaml:"state,omitempty" json:"state,omitempty"`

	// System
	System bool `yaml:"system,omitempty" json:"system,omitempty"`

	// Uid
	Uid int `yaml:"uid,omitempty" json:"uid,omitempty"`

	// Umask
	Umask string `yaml:"umask,omitempty" json:"umask,omitempty"`

	// UpdatePassword
	UpdatePassword string `yaml:"update_password,omitempty" json:"update_password,omitempty"`
}

type UserResult struct {
	Raw string

	// Append
	Append bool `yaml:"append,omitempty" json:"append,omitempty"`

	// Comment
	Comment string `yaml:"comment,omitempty" json:"comment,omitempty"`

	// CreateHome
	CreateHome bool `yaml:"create_home,omitempty" json:"create_home,omitempty"`

	// Force
	Force bool `yaml:"force,omitempty" json:"force,omitempty"`

	// Group
	Group int `yaml:"group,omitempty" json:"group,omitempty"`

	// Groups
	Groups string `yaml:"groups,omitempty" json:"groups,omitempty"`

	// Home
	Home string `yaml:"home,omitempty" json:"home,omitempty"`

	// MoveHome
	MoveHome bool `yaml:"move_home,omitempty" json:"move_home,omitempty"`

	// Name
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	// Password
	Password string `yaml:"password,omitempty" json:"password,omitempty"`

	// PasswordExpireMax
	PasswordExpireMax int `yaml:"password_expire_max,omitempty" json:"password_expire_max,omitempty"`

	// PasswordExpireMin
	PasswordExpireMin int `yaml:"password_expire_min,omitempty" json:"password_expire_min,omitempty"`

	// Remove
	Remove bool `yaml:"remove,omitempty" json:"remove,omitempty"`

	// Shell
	Shell string `yaml:"shell,omitempty" json:"shell,omitempty"`

	// SshFingerprint
	SshFingerprint string `yaml:"ssh_fingerprint,omitempty" json:"ssh_fingerprint,omitempty"`

	// SshKeyFile
	SshKeyFile string `yaml:"ssh_key_file,omitempty" json:"ssh_key_file,omitempty"`

	// SshPublicKey
	SshPublicKey string `yaml:"ssh_public_key,omitempty" json:"ssh_public_key,omitempty"`

	// Stderr
	Stderr string `yaml:"stderr,omitempty" json:"stderr,omitempty"`

	// Stdout
	Stdout string `yaml:"stdout,omitempty" json:"stdout,omitempty"`

	// System
	System bool `yaml:"system,omitempty" json:"system,omitempty"`

	// Uid
	Uid int `yaml:"uid,omitempty" json:"uid,omitempty"`
}

func (m *User) Run() error {
	raw, err := ansible.Execute(m.ModuleName, m.Params, &m.Result)
	m.Result.Raw = raw
	return err
}

func NewUser() *User {
	return &User{
		ModuleName: "user",
	}
}
